### ISSUE TITLE
Перевести статью "From &str to Cow"

### ISSUE THREAD

**Issue by alekseysidorov** [ruRust/rustycrate.ru#107]
http://blog.jwilm.io/from-str-to-cow/

На самом деле хоть и достаточно базовые вещи говорятся, но о них почему-то все забывают. Да и данный подход, к примеру, легко на С++ переносится. Хотя я чисто такого же шаблона Cow на плюсах не видел ни разу, там немного другой подход наблюдается.

Набросок живет здесь:
https://github.com/alekseysidorov/articles/blob/master/rust/translations/cow.md

**Comment by mkpankov** [comment]
#109
