### ISSUE TITLE
Перевести "Introducing MIR"

### ISSUE THREAD

**Issue by DarkEld3r** [ruRust/rustycrate.ru#108]
http://blog.rust-lang.org/2016/04/19/MIR.html

Попытаюсь взяться, хотя статья/новость весьма объёмная...

**Comment by mkpankov** [comment]
@DarkEld3r как дела, есть успехи?

**Comment by DarkEld3r** [comment]
Боюсь, что я перегорел. (:

В какой-то момент нахватал статей под переводы и все они в заброшенном состоянии. Разве что "мифы и легенды о переполнении" добить хочу, но и там дело идёт не особо быстро. Но на следующей неделе закончу и выложу на ревью.

А тут статус "в прогрессе", пожалуй, надо убрать. (:

**Comment by mkpankov** [comment]
Закрываю на данный момент, переоткрывай если что
