### ISSUE TITLE
[некорректно] Некорректное отображение на сайте

### ISSUE THREAD

**Issue by SunyDays** [ruRust/rustycrate.ru#110]
В статье `От &str к Cow` в разделе [Нас спасет типаж Cow](https://rustycrate.ru/%D0%BE%D0%B1%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5/2016/04/28/from-str-to-cow.html#%D0%9D%D0%B0%D1%81-%D1%81%D0%BF%D0%B0%D1%81%D0%B5%D1%82-%D1%82%D0%B8%D0%BF%D0%B0%D0%B6-cow) некорректно отображаются списки. Вместо выделения элементов и переносов строк - текст разделённый `*`. Если открыть [фаил статьи](https://github.com/ruRust/rustycrate.ru/blob/master/_posts/2016-04-28-from-str-to-cow.md), то там всё впорядке.

Windows 2012r2, Firefox 46.0
Debian 8, Firefox 43.0

**Comment by mkpankov** [comment]
Спасибо, исправил
