### ISSUE TITLE
Перевести "Why is a Rust executable large?"

### ISSUE THREAD

**Issue by l4l** [ruRust/rustycrate.ru#114]
[Линка](https://lifthrasiir.github.io/rustlog/why-is-a-rust-executable-large.html)

Постараюсь перевести(в течении недели), если что -- тыкайте палкой, статья действительно крутая

**Comment by ozkriff** [comment]
Мне статья показалась странной, потому что про слона в комнате - статическое связывание по-умолчанию - говорится не в самом начале, а ближе к концу и вскользь как-то.

**Comment by l4l** [comment]
Да, воды, по правде говоря много, но тем не менее информативна за счет размера, хотел выкинуть всякие лирические отступления и оставить только техническую часть без воды

**Comment by mkpankov** [comment]
@ozkriff согласен с этим комментарием, но считаю, что изменение такой вещи тянет на переписывание статьи. Лучше сделать перевод этой статьи, чем написать с нуля никакую :)
