### ISSUE TITLE
Перевод rust by example

### ISSUE THREAD

**Issue by Gordon-F** [ruRust/rustycrate.ru#122]
В процессе обучения языка программирования Rust занимаюсь переводом Rust by example.

До окончания перевода еще далеко, поэтому буду рад любой помощи! 

[Репозиторий](https://github.com/Gordon-F/rust-by-example-ru)
[Ход перевода](https://github.com/Gordon-F/rust-by-example-ru/issues/1)

**Comment by mkpankov** [comment]
Приветствую!

Хочу заметить, что также есть неоконченный перевод у @suhr : https://github.com/suhr/rust-by-example/issues/2 . Возможно, по согласованию с ним, стоит взять оттуда некоторые главы.

**Comment by mkpankov** [comment]
Также предлагаю захостить где-то веб-версию книги. Проще всего на GitHub Pages. Тогда можно будет поставить на неё ссылку на rustycrate.ru.

**Comment by Gordon-F** [comment]
@mkpankov Добрый день! Я уже связался с @suhr в gitter. Если получу его согласие, возьму его перевод и обьеденю со своим.

На GitHub Pages планировал захостить перевод, когда он будет закончен. Пока можно собирать и локально.

**Comment by mkpankov** [comment]
@Gordon-F на самом деле, поскольку перевод - это очень длительный проект, наличие опубликованных на сайте промежуточных результатов помогает читателям видеть прогресс. Ну и вообще - читать на русском хотя бы те части, которые переведены. И помощников так найти проще.

Например, TRPL мы порядка года переводили. При этом каждая версия автоматически разворачивается на сайт - ничего руками делать каждый раз не надо.

**Comment by suhr** [comment]
> Возможно, по согласованию с ним, стоит взять оттуда некоторые главы.

Я не против, опенсурс же. Правда, перевод старый, так что многое придётся делать заново.

**Comment by Gordon-F** [comment]
@mkpankov Над CI работаю. Пытаюсь правильно настроить Travis. С авторизацией пока проблема.

@suhr Спасибо! Сейчас, пока, солью как есть. После того, как перевод будет закончен (черновой вариант) начну его редактировать.

**Comment by suhr** [comment]
Не забудь прикрутить Reviewable.

**Comment by Gordon-F** [comment]
@suhr ты о https://reviewable.io ?

**Comment by suhr** [comment]
Именно о нём.

**Comment by Gordon-F** [comment]
@suhr Спасибо! Не слышал о таком инструменте.

**Comment by mkpankov** [comment]
@Gordon-F если будет засада с CI - пиши в Gitter, постараюсь помочь.

**Comment by Gordon-F** [comment]
@mkpankov настроил CI. Спасибо!

**Comment by mkpankov** [comment]
Круто!

Пиши анонс проекта - приму PR. И давайте добавим [ссылку на книгу](https://github.com/ruRust/rustycrate.ru/blob/master/_includes/header.html#L49-L53) на сайт.

**Comment by mkpankov** [comment]
Тут тоже всё нужное уже сделали, закрываю.
