### ISSUE TITLE
Перевод документации по Cargo

### ISSUE THREAD

**Issue by Gordon-F** [ruRust/rustycrate.ru#123]
Кроме перевода [rust by example](https://github.com/ruRust/rustycrate.ru/issues/122) так же занимаюсь переводом [документации по Cargo](http://doc.crates.io/).

[Ход перевода](https://github.com/Gordon-F/cargo-docs-ru/issues/1)
[Репозиторий](https://github.com/Gordon-F/cargo-docs-ru/)

**Comment by mkpankov** [comment]
Я добавил ссылку, напиши где-нибудь в самой документации, что это действующий проект перевода документации Cargo, чтобы люди могли найти репозиторий и поучаствовать. Задачу тогда закроем.

**Comment by Gordon-F** [comment]
@mkpankov Спасибо! Там ссылка на репозиторий есть по кнопке "Fork me on GitHub". Думаешь еще стоит где-то добавить?

**Comment by mkpankov** [comment]
@Gordon-F а, не заметил. Нормально, закрываю.
