### ISSUE TITLE
Перевод поста из официального блога Rust "Инкрементальная компиляция"

### ISSUE THREAD

**Issue by LooMaclin** [ruRust/rustycrate.ru#131]
Перевод поста из официального блога Rust "Инкрементальная компиляция": https://blog.rust-lang.org/2016/09/08/incremental.html
Задачу создал для координации. Она будет закрыта после окончания перевода и создания соответствующего PR.

**Comment by mkpankov** [comment]
На данный момент закрываю по отсутствию прогресса, если что переоткрывай
