### ISSUE TITLE
Прикрутить проверку орфографии

### ISSUE THREAD

**Issue by mkpankov** [ruRust/rustycrate.ru#132]
https://github.com/hcodes/yaspeller

**Comment by vessd** [comment]
Эта задача актуальна или обходимся typograf и eyo?

**Comment by mkpankov** [comment]
Это разные вещи.
Типограф делает правильное типографирование - например, ставит тире там где оно должно быть (вместо дефиса).
Так что актуально, но Яндекс.Спеллер использовать не хочется.

**Comment by vessd** [comment]
Почему?

**Comment by mkpankov** [comment]
Да я думал там на каждой странице надо про него писать.

**Comment by vessd** [comment]
Ну если это был единственный вопрос, то я предлагаю его всё же прикрутить.

**Comment by mkpankov** [comment]
Давай прикрутим.
