### ISSUE TITLE
Перенести словарь терминов на rustycrate.ru

### ISSUE THREAD

**Issue by ozkriff** [ruRust/rustycrate.ru#148]
Есть мысль [словарь терминов](https://github.com/ruRust/rust_book_ru/wiki/%D0%A1%D0%BB%D0%BE%D0%B2%D0%B0%D1%80%D1%8C-%D1%82%D0%B5%D1%80%D0%BC%D0%B8%D0%BD%D0%BE%D0%B2) перенести на rustycrate.ru и ссылку куда-то на видное место положить в шапке. А то полезная штука, а про нее полтора человека знают.

**Comment by mkpankov** [comment]
Готово: https://github.com/ruRust/rustycrate.ru/commit/d596f6bbf72fb878a4cc56deb4bd4af79d1c1171
