### ISSUE TITLE
Перевести Pretty State Machine Patterns in Rust

### ISSUE THREAD

**Issue by mersinvald** [ruRust/rustycrate.ru#149]
Берусь за перевод Pretty State Machine Patterns in Rust (https://hoverbear.org/2016/10/12/rust-state-machine-pattern/), по окончании хочу получить ревью на перевод чтобы впоследствии оформить публикацию на HabraHabr

**Comment by mkpankov** [comment]
Как дела?

**Comment by mersinvald** [comment]
@mkpankov до начала сессии успел только разобрать исходник, как кончится -- продолжу.

**Comment by Gexon** [comment]
ипать! пол года чтоли переводите или я путаю что-то?

**Comment by Gexon** [comment]
предлагаю взять огонь на себя))))
тоесть перевести это после публикации изменения размеров картинок

**Comment by Gexon** [comment]
Делаю отвод в пользу
Ilya Bogdanov@vitvakatu

**Comment by vitvakatu** [comment]
Отвод принял :smile:

**Comment by mkpankov** [comment]
@Gexon не ругайся в issues пожалуйста

**Comment by mkpankov** [comment]
#199
