### ISSUE TITLE
Добавление метатегов для twitter

### ISSUE THREAD

**Issue by Safort** [ruRust/rustycrate.ru#153]
Будет очень удобно, если на странице статьи будут теги для социальных сетей. Например, если я хочу поделиться ссылкой в твиттере, то он автоматически подгрузит заголовок, описание и картинку статьи сам, делая твиттопост более информативным.
Тут можно найти описание https://dev.twitter.com/cards/getting-started

**Comment by Gordon-F** [comment]
Получается нужно добавить description в каждый пост (в каждый md файл)? Или только добавить только для новых как правило?

**Comment by mkpankov** [comment]
@Gordon-F это никак не отразится на файлах публикаций. Краткое содержимое и так сейчас извлекается, чтобы вставить его в `<meta name="description" content="...">`. Это делается [тут ](https://github.com/ruRust/rustycrate.ru/blob/master/_includes/head.html#L39)
