### ISSUE TITLE
Оптимизация сайта

### ISSUE THREAD

**Issue by mkpankov** [ruRust/rustycrate.ru#160]
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Frustycrate.ru&tab=desktop
https://gtmetrix.com/reports/rustycrate.ru/FhAQAKd3
https://www.webpagetest.org/result/161203_BM_1MYJ/
https://tools.pingdom.com/#!/VmEYT/https://rustycrate.ru

Починить все сильно плохие оценки, сделать чтобы итоговая оценка была хотя бы "средне".

**Comment by vessd** [comment]
Можно склеить иконки в одно изображение и выводить с помощью стилей css.
Все другие оптимизации, доступные для сайта на jekyll, уже выполнены.
Все анализаторы так или иначе предлагают выпилить встроенный чат.

**Comment by mkpankov** [comment]
Насколько сложно будет склеить?

Кстати, эта оптимизация будет неактуальна по мере перехода браузеров на HTTP/2, а он уже идёт полным ходом.

Возможно стоит закрыть.

**Comment by vessd** [comment]
Это не сложно, но я не разобрался как тут добавить свой css.

**Comment by mkpankov** [comment]
Закрываю, т.к. все основные оптимизации сделаны, и прогресса больше нет.
