### ISSUE TITLE
Рассмотреть применение ngx_http_gzip_static_module

### ISSUE THREAD

**Issue by mkpankov** [ruRust/rustycrate.ru#165]

**Comment by vessd** [comment]
Как я понимаю доступ к конфигурации nginx только у тебя?

**Comment by mkpankov** [comment]
@vessd да

**Comment by vessd** [comment]
тогда не то что бы этот issue был уместен в этом репозитории)

**Comment by mkpankov** [comment]
Мне всё равно надо это помнить

**Comment by mkpankov** [comment]
Скорость работы сайта на данный момент достаточна, не будем делать.
