### ISSUE TITLE
Завести отдельную страницу с правилами

### ISSUE THREAD

**Issue by ozkriff** [ruRust/rustycrate.ru#167]
Взять правила из https://rustycrate.ru/новости/2015/11/04/hello-world.html#pravila, вынести на отдельную страницу и дать на нее ссылку в меню "Материалы сообщества".

Возможно, на этой же странице под правилами можно сделать главу с рекомендациями, вроде:
- ["Как правильно задавать вопросы (esr)"](http://maddog.sitengine.ru/smart-question-ru.html) (в идеале какой-то менее претенциозный аналог, без сотни упоминаний слова "хакер");
- Повторить вопрос на форуме, если в чате на него никто не ответил и он "утонул" в переписке;
- Если код больше 10 (?) строк, скидывать его через gist/playpen, причем для гистов использовать не сырые, а md-ссылки, что бы gitter не раскрывал их на пол экрана;
- [Стараться минимизировать примеры кода в вопросах](http://ru.stackoverflow.com/help/mcve);
- Не скидывать в гиттер кучу раскрытых gif картинок, потому что они могут неплохо так завесить браузер на не самом новом железе;
- и т.п.

**Comment by mkpankov** [comment]
@ozkriff вроде сделано, или хочешь ещё что-то добавить?

**Comment by ozkriff** [comment]
Не, меня теперь все устраивает тут :)
