### ISSUE TITLE
Сделать кнопку "Вверх"

### ISSUE THREAD

**Issue by mkpankov** [ruRust/rustycrate.ru#173]
Должно увеличить вовлечение людей и мотивировать их ходить по сайту.

**Comment by mkpankov** [comment]
Решили вместо этого сделать кнопку "вверх" сборку

**Comment by vessd** [comment]
Возможно стоит переименовать этот issue

**Comment by vessd** [comment]
А есть какие-нибудь конкретные пожелания? Форма/цвет?

**Comment by mkpankov** [comment]
Да как на хабре примерно.
