### ISSUE TITLE
Убрать одну из ссылок на словарь терминов

### ISSUE THREAD

**Issue by Gordon-F** [ruRust/rustycrate.ru#177]
Думаю, что стоит убрать одну из ссылок на словарь терминов.

Одна находится в подменю "Книги", другая в "Материалы сообщества". 

Предлагаю убрать из "Материалы сообщества".

**Comment by vessd** [comment]
Я предлагаю убрать ссылку из раздела "Книги".
Словарь терминов не является книгой. Он по сути результат труда сообщества, так что его место в материалах сообщества.

**Comment by mkpankov** [comment]
Зачем её откуда-то убирать? Её можно найти и там и там, так и задумано - чтобы людям было проще обнаружить.

**Comment by Gordon-F** [comment]
@mkpankov может лучше оставить в одном месте и добавить ее в "Руководство по участию в проектах" ?

Если считаешь, что она нужна и там и там, то задачу можно закрывать.

**Comment by mkpankov** [comment]
Я просто не понял, кому она мешает :smile:

**Comment by mkpankov** [comment]
Фишка в том, что люди могут и не участвовать в наших проектах, но вот они переводят что-то своё и натыкаются на словарь.
В книгах она потому, что часто нужна при переводе книг.
В материалах она потому, что нужна как справочник в разных ситуациях.
Как-то так.

**Comment by Gordon-F** [comment]
@mkpankov Она не кому не мешает, просто странно получается. Если это контент, который необходимо показать всем, то, думаю, его нужно убрать из второго уровня вложенности. 

А в меню очень нужна ссылка на stackoverflow ? Место занимает :)

**Comment by vessd** [comment]
Вот ссылку на stackoverflow я бы не трогал. Многие до сих пор не знают, что у него есть ru поддомен.

**Comment by mkpankov** [comment]
Дело в том, что физически поместить её на первый уровень тяжело. Всё, что сейчас на первом уровне - важнее, чем словарь.

**Comment by vessd** [comment]
По моему ссылка "Блог" довольно спорная. Её можно поместить в картинку с контейнером и на этом ограничиться. Само слово на мой взгляд лишнее.

**Comment by Gordon-F** [comment]
@vessd Она уже в картинке с контейнером. По сути эта ссылка "На главную".

**Comment by vessd** [comment]
Ну вот я и предлагаю оставить её только в картинке, а само слово убрать.

**Comment by Gordon-F** [comment]
@mkpankov как насчет убрать ссылку "Блог" ?

**Comment by mkpankov** [comment]
Я против, кликабельность логотипа и куда он переходит не очевидно
