### ISSUE TITLE
Перенести материалы сообщества на поддомен rustycrate.ru

### ISSUE THREAD

**Issue by Gordon-F** [ruRust/rustycrate.ru#178]
Предлагаю перенести все материалы сообщества (книги, переводы документации) на поддомен для rustycrate.ru.

Например, rustbook.rustycrate.ru или rustycrate.ru/book

**Comment by mkpankov** [comment]
Я думаю над тем, чтобы сделать домен rust.rustycrate.ru, а материалы положить в rust.rustycrate.ru/book и rust.rustycrate.ru/by-example.

У нас дальше будет расширяться набор тем, которые мы поддерживаем в сообществе - вот по темам можно и поддомены заводить.

**Comment by mkpankov** [comment]
По факту набор тем расширен не был, откладываю эту идею.

**Comment by Gordon-F** [comment]
@mkpankov перенести текущий материал нет желания ? книгу, rbe ?

**Comment by mkpankov** [comment]
Не особо, зачем?

**Comment by Gordon-F** [comment]
@mkpankov Изначально issue было об этом. Решил уточнить :)

**Comment by mkpankov** [comment]
Я понимаю что задача была об этом )

Вопрос в том откуда взялась необходимость в задаче. Иными словами, какую проблему мы решаем?

**Comment by Gordon-F** [comment]
@mkpankov да по факту только вес домена rustycrate.ru
