### ISSUE TITLE
Перенести правила перевода на сайт

### ISSUE THREAD

**Issue by Gordon-F** [ruRust/rustycrate.ru#185]
Было бы неплохо перенести страницу с [правилами перевода книги](https://github.com/ruRust/rust_book_ru/wiki/Правила) на сайт. 

Общие правила перевода не будут лишними.

**Comment by mkpankov** [comment]
Это довольно просто сделать: можно посмотреть на словарь терминов в `dictionary.md` и сделать аналогично.
