### ISSUE TITLE
Перевести FAQ

### ISSUE THREAD

**Issue by mkpankov** [ruRust/rustycrate.ru#19]
https://github.com/rust-lang/rust-www/pull/202

**Comment by D101101** [comment]
https://www.rust-lang.org/faq.html
https://github.com/rust-lang/rust-www/blob/master/faq.md

**Comment by mkpankov** [comment]
Добавлять к нам уже не надо, нужно перевести на официальном сайте.

https://github.com/rust-lang/rust-www/blob/master/ru-RU/faq.md

https://github.com/rust-lang/rust-www/blob/master/en-US/faq.md

**Comment by mkpankov** [comment]
Это уже не наша задача как таковая, закрываю.
