### ISSUE TITLE
Перелицензирование статей и книг

### ISSUE THREAD

**Issue by Vinatorul** [ruRust/rustycrate.ru#193]
Сейчас у большинства (если не всех) статей отсутствует какая-либо информация о лицензиях на тексты. Имеет смысл оформить некоторую лицензию, которая бы ограничивала круг распространения публикаций с сайта.

Предлагаю здесь это обсудить, заодно здесь же можно будет собрать "подписи" авторов прошлых работ.

**Comment by vessd** [comment]
Хорошее предложение, вот эта лицензия подойдёт?
https://choosealicense.com/licenses/cc-by-4.0/

**Comment by Gordon-F** [comment]
Часть статей является переводом. Насколько я знаю, лицензия перевода должна соответствовать лицензии автора статьи. 

Если у оригинальной статьи нет лицензии, что делать тогда ?

**Comment by vessd** [comment]
Можно написать автору и спросить про лицензию, если он не отвечает, то считать, что unlicensed.
Не вижу препятствий по смене лицензии, если это не запрещает лицензия оригинала.

**Comment by vessd** [comment]
В крайнем случае мы можем сделать ещё один тег в шапке, который будет указывать лицензию.

**Comment by Gordon-F** [comment]
@vessd тег в шапке с лицензией определенно нужно

**Comment by vessd** [comment]
Хм, я ошибся, если автор не отвечает по поводу лицензии, то видимо нужно ссылаться на [No License](https://choosealicense.com/no-license/).
И мы действительно не можем вносить изменения в такую публикацию. Хм...

**Comment by shmutalov** [comment]
От автора нужно именно требовать лицензию, а не просто разрешение на перевод?

**Comment by vessd** [comment]
Думаю разрешения достаточно, но в таком случае нужно понять, как можно лицензировать перевод.
Но если есть лицензия, то спрашивать не нужно :)

**Comment by shmutalov** [comment]
![image](https://cloud.githubusercontent.com/assets/8098898/23653431/590ff51c-034e-11e7-8d9b-be94dcc16456.png)

**Comment by sirikid** [comment]
> Не вижу препятствий по смене лицензии, если это не запрещает лицензия оригинала.

Так и есть, плюс публикуется *перевод*, а не сама статья.

> Можно написать автору и спросить про лицензию, если он не отвечает, то считать, что unlicensed.

Лучше написать что мы (rustycrate) ничего про лицензию не знаем и ссылаться на нас в этом плане не следует и быть готовыми удалить статью по запросу, дальнейшее распространение такого перевода возможно только на свой страх и риск.

**Comment by Gordon-F** [comment]
@sirikid Правильно понимаю, что ты предлагаешь всю ответственность за лицензии на статьи переносить на авторов перевода ?

**Comment by vessd** [comment]
@Gordon-F как я понял те статьи, для которых мы каким-либо образом не сможем узнать разрешение на перевод, предлагается всё равно переводить и выкладывать с пометкой о том, что мы (как сообщество) не знаем лицензии оригинала и готовы удалить перевод по запросу.
На счёт того на сколько в таком случае защищены авторы перевода я не возьмусь судить.

**Comment by Gordon-F** [comment]
@mkpankov Как в итоге будем делать? Добавлять новое поле, которе по дефолту "Без лицензии" ? Которые будет обновляться авторами статьи.

**Comment by vessd** [comment]
@Gordon-F я предлагаю по дефолту ставить `Creative Commons Attribution 4.0`, а если кто-то хочет что-то особенное, то это нужно будет обсудить.

**Comment by mkpankov** [comment]
@Gordon-F да. Не только перевода, для статей то же.

@vessd мы не можем по умолчанию лицензировать хоть как-то, потому что сейчас материалы лицензированы никак.

**Comment by vessd** [comment]
@mkpankov это понятно.
@Vinatorul как раз и предлагал собрать подписи авторов предыдущих работ для лицензирования.
Но для начала надо решить, какую лицензию использовать, и где мы на неё будем ссылаться.

**Comment by mkpankov** [comment]
@Vinatorul согласен насчёт сбора подписей.

По умолчанию предлагаю всё же CC-BY-SA, а не CC-BY, т.к. не нужно разрешать перелицензирование.

**Comment by mkpankov** [comment]
Коллеги, я думаю нужно создать простую гугл-форму с текстом, который обобщает это обсуждение: зачем это нужно, какова наша политика относительно нелиценизрованных статей, что с переводами. Там же сделать галочку "Я согласен на перелицензирование" и разослать форму по почте (на те адреса, что в коммитах).

Кто возьмётся?

**Comment by mkpankov** [comment]
Решение такое: по запросу автора статьи сменим лицензию на прошлую статью. Специальной поддержки делать не будем.

Если не согласны - делайте PR с добавлением поля в шапку статьи и гугл-форму.
