### ISSUE TITLE
Перевод "What Are Sum, Product, and Pi Types?"

### ISSUE THREAD

**Issue by vessd** [ruRust/rustycrate.ru#198]
Берусь за перевод "[What Are Sum, Product, and Pi Types?](http://manishearth.github.io/blog/2017/03/04/what-are-sum-product-and-pi-types/)".

**Comment by vessd** [comment]
Перевод откладывается на неопределённый срок.
Мои наработки сохранены в https://github.com/ruRust/rustycrate.ru/tree/types

**Comment by mkpankov** [comment]
Закрываю, т.к. прошло 2 месяца и никто не заинтересовался продолжением работы.

**Comment by vessd** [comment]
А в чате объявление было? Хотя я уже не уверен, что статья актуальна для перевода.

**Comment by mkpankov** [comment]
Сделал объявление, может кто закончит.
