### ISSUE TITLE
Актуализировать статью про IDE

### ISSUE THREAD

**Issue by Gordon-F** [ruRust/rustycrate.ru#200]
После выхода RLS необходимо обновить [статью про IDE](https://rustycrate.ru/%D1%80%D1%83%D0%BA%D0%BE%D0%B2%D0%BE%D0%B4%D1%81%D1%82%D0%B2%D0%B0/2015/12/04/ide-for-rust.html), актуализировав информацию.

Как минимум, для VSCode нужно заменить расширение с RustyCode (не поддерживается) на vscode-rust.

**Comment by vessd** [comment]
- описать установку с использованием `rustup`
 - устанавливать `racer` и `rustfmt` через `cargo install`
 - секция про хоткеи для VSCode устарела

**Comment by mkpankov** [comment]
* объединить общие разделы для всех редакторов в один:
  * установка Rust
  * установка racer
  * настройка окружения

**Comment by BORN2LOSE** [comment]
Начну обновлять статью.

**Comment by BORN2LOSE** [comment]
Пока редактировал статью, набрел на мысль: "Нужно ли писать о том, как установить редактор для своего дистрибутива/винды/макинтоша" ?
Думаю, что сначала операторам ЭВМ следует научиться обращаться с репозиториями своего дистрибутива или ОС.
Мануал может вырости до: "Устанавливаем Gentoo GNU/Linux и подготавливаем к работе на языке Rust".

**Comment by vitvakatu** [comment]
ИМХО установка редакторов не нужна. Только настройка дополнений и установка самого языка.

**Comment by mkpankov** [comment]
> ИМХО установка редакторов не нужна. Только настройка дополнений и установка самого языка.

Согласен.

**Comment by BORN2LOSE** [comment]
Можно закрыть задачу https://github.com/ruRust/rustycrate.ru/pull/247
