### ISSUE TITLE
Перевод Math with distances in Rust: safety and correctness across units

### ISSUE THREAD

**Issue by vitvakatu** [ruRust/rustycrate.ru#204]
Начал перевод [Math with distances in Rust](https://ferrisellis.com/posts/rust-implementing-units-for-types/), а также [Communicating intent](https://github.com/jaheba/stuff/blob/master/communicating_intent.md)

**Comment by mkpankov** [comment]
@vitvakatu есть успехи?

**Comment by vitvakatu** [comment]
@mkpankov Communicating intent переведен уже давненько, перевод Math with distances in Rust в процессе (где-то 30% выполнено). Подзабыл про него, честно говоря, пока была сессия, думаю в течение недели должен доделать.

**Comment by mkpankov** [comment]
Пока закрываю, если есть желание продолжить - переоткрывайте
