### ISSUE TITLE
Добавить канал поддержки новичков

### ISSUE THREAD

**Issue by mersinvald** [ruRust/rustycrate.ru#210]
Давайте обсудим возможность добавления дополнительной комнаты в Gitter сообществе для поддержки новичков, приходящих в язык.

Плюсы:
* Это разгрузит General, в котором обсуждаются проблемы опытных расташианинов, статьи, новости и анонсы, важные для сообщества языка.
* Выделение отдельного канала поддержки с психологически устойчивыми членами сообщества поможет избежать агрессии в сторону новичков

Минусы:
* Возможно время реакции на вопрос увеличится

**Comment by alexander-irbis** [comment]
> Возможно время реакции на вопрос увеличится

Не думаю, что существенно, если там будут сидеть всё те же, кто помогает новичкам на основном канале.

**Comment by Vinatorul** [comment]
Хорошая идея, я, например, не читаю `general`, т.к. там сложно уследить за всем и довольно много специфичных вещей, а на канале для новичков бы сидел и помогал с простыми вопросами. Думаю, что я не один такой.

**Comment by chabapok** [comment]
А почему канал для новичков? Может наоборот создать канал для опытных, а дженерал оставить всем? :))

Вообще, опасаюсь чтобы этого не случилось на данном историческом этапе развития.

Слишком мало людей, чтобы это делать. Создание такого канала изолируют новичков, и людям опытным будет влом помогать новичкам. Ну знаете, бывает так, что вопрос видишь, ответ знаешь - а отвечать влом. И когда новичок приходит в общий канал, там вопрос видят пару десятков человек, и вероятность, что хоть кому-нибудь не влом ответить - выше. А если для таких вопросов будет отдельный канал, то эти пару десятков человек на такой канал просто не подпишутся. В этом случае, приток в rust новых людей должен быть настолько большим, чтобы в канале для новичков всегда были любители отвечать на простые вопросы. В настоящее время таких обьемов у нас просто нет. Будет примерно как на форуме -  скорость реакции вообще потрясающе низкая получается.

По этой причине, появление такого канала:
- не в интересах  самих новичков
- не в интересах развития языка
- не в интересах развития сообщества
- в интересах гуру. Но только тех гуру, которые не заинтересованы в развити языка и сообщества

Такой канал надо будет вводить когда реально возрастут обьемы настолько, что новички и опытные люди начнут друг другу мешать. Тогда можно будет не бояться, что проблема будет актуальна.

**Comment by mersinvald** [comment]
Как в чате уже упоминали модель которую используют в сабреддите /r/rust:
* Тред для простых вопросов
* Треды в сабреддите для новостей, анонсов и сложных вопросов, на которые не смогли ответить в первом

В нашем случае каналы вместо тредов можно точно так же разделить по содержанию

**Comment by chabapok** [comment]
Вообще, форумом не пользуются, потому что движок написан ради рюшечек. Если поставить туда нормальный "традиционный" движок, то "проблемы опытных расташианинов, статьи, новости и анонсы, важные для сообщества языка" будет удобней обсуждать там и люди будут этим пользоваться.

**Comment by mersinvald** [comment]
@chabapok есть такое опасение, но все равно стоит подумать над тем как разделить важный новостной контент от однотивных вопросов и листингов на полторы страницы. Важный и интересный контент очень быстро улетает вверх по истории сейчас.

Вариант канал для новостей и гуру и general для новичков -- по сути то же самое только с другого ракурса, суть не меняется :)

Насчет форума: есть люди, которым просто неудобно пользоваться форумами в силу специфики оных. У меня есть клиент на десктопе и телефоне, открытый параллельно с телеграммом, и это удобно. Думаю, я не один такой)

**Comment by alexander-irbis** [comment]
Можно подойти с обратной стороны - для анонсов и новостей как раз сделать специальный канал, куда больше ничего не пишется, за важной информацией будет значительно проще следить.

**Comment by chabapok** [comment]
@mersinvald ключевая фраза "на данном этапе развития". Когда-нибудь, если сообщество будет расти, такое разделение сделать прийдется. Вопрос в том, дорасло сообщество до такого объема, или нет.

Сколько таких хороших людей, как @Vinatorul в сообществе? Если он один - плохо. Если некоторое достаточное количество есть - можно так делать. Если избыток - нужно.

**Comment by kgv** [comment]
Не вижу принципиальной разницы - какой канал выделять, главное отделить "общие аспекты, касающиеся языка" (не только новости и анонсы) и "частное решение вопросов в рамках одной конкретной задачи".

**Можно ввести такую комнату на пробный период.** Полностью согласен с тем, что ответы на вопросы новичков - очень важно для развития сообщества, и если, действительно, новички будут обделены вниманием, то вернуть все как было.

**Comment by alexander-irbis** [comment]
На самом деле ситуация не настолько критична. Тех, кто способен отвечать на вопросы совсем уж новичков - значительно больше. В том числе на них могут отвечать и те, кто сам недавно только разбирал что-то похожее, и самим новичкам может быть интересно найти ответ на простой вопрос, на который они ещё не знают ответа, но чувствуют силу решить эту задачу.

Пока не попробуем - не узнаем.

**Comment by vitvakatu** [comment]
Поддерживаю @alexander-irbis и @mersinvald одновременно. По моему мнению, наилучшими решением будет три канала: для новичков, где скорей всего будут сидеть те, у кого хватает нервов отвечать на порой глупые вопросы (я например), второй -general, для более сложных вопросов, обсуждений. Третий - для новостей и объявлений, чтобы это не затерялось в других каналах.
Ну и оффтопик, удалять его будет глупым решением :)
cc @mkpankov

**Comment by antage** [comment]
Разделение каналов - это хорошо. Не раз наблюдал, что когда какая-то технология становится популярной и в чат/рассылку приходит много новичков с простыми вопросами, опытные начинают уходить, потому что ни отвечать, ни читать это им становится неинтересно.

**Comment by shmutalov** [comment]
Я считаю, что сообщество ещё не настолько развито, чтоб прям так выделять новичков отдельно. И вообще, мода на каждый чих по новому каналу то же не разделяю. Алго пустует. Солидарен с @chabapok. Поддерживаю идею отделения новостей от обсуждения проблем.

**Comment by Gexon** [comment]
Нужно больше каналов!

Смотрю мистер панков не учится на ошибках.
Полагаю он сильно занят учебой и не до нас ему.

**Comment by Gexon** [comment]
Солидарен с Шерзодом, а новости я получаю в телеграмму и это норм. Жаль что мои новости не транслируются в соцсети по причине "твои новости не представляют важности".

**Comment by Gexon** [comment]
Осознал коменты выше как то по колхозной заимки вне серьёзные. Прошу извинить всех и мистера Панкова в частности.

По существу, "нужно больше каналов!" я уже писал.
Кто то общается в канале секюре и алгоритмы?
Нет? Так может хватит думать в одной плоскости. Я предлагал конкретные предложения по улучшению сайта, но мои предложения были проигнорированы. Это как воздушный шарик, надавил в одном месте, в другом вылезло. Только вот хватит надавливать на одно и то же место. Срочно нужен транслятор новостей в соцсети, без модерации панкова.

**Comment by mersinvald** [comment]
@Gexon думаю это другая задача для обсуждения. Добавь Issue с конструктивным предложением и линкани сюда, может?

**Comment by mkpankov** [comment]
@Gexon что там было проигнорировано? Ты хотел сделать механизм для этой трансляции. Где он?

**Comment by mkpankov** [comment]
@Gexon какие новости не транслируются? Давай без обид, создай отдельную задачу для обсуждения этого.

**Comment by mkpankov** [comment]
Позже сделаем опрос, чтобы понять, насколько велик компромисс: сколько людей пойдёт в новый канал, скольким людям сейчас мешает нагруженность general и т.д.

Тем временем, 
* Кто хочет читать новости, но не хочет читать большие обсуждения - чем не устраивают соцсети и телеграм? Там только новости.

**Comment by shmutalov** [comment]
Новости в телеграм это круто, спасибо большое за это.

**Comment by mkpankov** [comment]
Опрос на тему: https://goo.gl/forms/q6p5aLFzOHSztv4E2

**Comment by mkpankov** [comment]
Ребята, есть ещё такая идея: давайте соберём статистику по простым вопросам в general за неделю. Для этого нужно сохранять ссылки на сообщения, в которых человек задаёт вопрос, который можно идентифицировать как отдельный вопрос. Т.е. не нужно все сообщения с вопросами сохранять, конечно. Только те, с которых начинается беседа. Потом мы эти вопросы отклассифицируем по сложности и поймём примерно, сколько сообщений выделится в новый канал.

Как вам идея? Сам я это не осилю сделать, поэтому нужна помощь тех, кто активно сидит в чате.

**Comment by ozkriff** [comment]
Я за - говори куда и в каком формате складывать.

**Comment by mkpankov** [comment]
Табличка: https://docs.google.com/spreadsheets/d/1jtwrQFjUGNtk36EVaj6Qe-X4pZUMYh-NYv2h5D1yk-U/edit?usp=sharing

Я думаю, кроме ссылки на сообщение ничего не нужно. Остальное при классификации достанем, если понадобится.

**Comment by ozkriff** [comment]
так, неделя сбора вопросов прошла

**Comment by mkpankov** [comment]
Отлично!

С этого момента новые вопросы в табличку не добавляем. Теперь давайте коллективно обрабатывать собранное.

К сожалению, вставить многострочные вопросы в табличку нормально не получается, поэтому работаем по ссылкам.

По сложности, я думаю, классификация такая:
- Простой. Ответ известен человеку с небольшим опытом использования Rust (от дней до 3 месяцев) или покрывается материалом нашего перевода официальной книги (http://rurust.github.io/rust_book_ru/), за исключением главы "Нестабильные возможности Rust", или покрывается материалом второго издания оригинала книги (https://rust-lang.github.io/book/second-edition/index.html), за исключением главы "Advanced features".
- Средний. Ответ известен человеку с заметным опытом использования Rust (от нескольких месяцев) или описан в любом месте нашего перевода или второго издания оригинала книги, или описан в сторонних статьях, постах в блогах и т.д.
- Сложный. Ответ известен человеку с большим опытом использования Rust и с опытом реализации компилятора или инструментов Rust, либо не известен даже ему, либо известен но не описан нигде в письменном виде.

**Comment by mkpankov** [comment]
Спасибо кто помогал классифицировать.

Сделал сводную таблицу и график:
https://docs.google.com/spreadsheets/d/1jtwrQFjUGNtk36EVaj6Qe-X4pZUMYh-NYv2h5D1yk-U/edit#gid=689429515

Это говорит о том, что больше половины вопросов - простые.

Поэтому предлагаю добавить канал для простых вопросов.

Пробный период - 3 месяца с момента создания.

Критерий успеха - 50 пользователей в канале, отсутствие простых вопросов в general спустя 3 месяца. Отсутствие простых вопросов измеряться будет таким же недельным замером (или если не потребуется точность, просто по показаниям участников general).

В шапке general напишем, что простые вопросы задавать в другом канале.

Есть проблема, что вопрос, который кажется простым задающему, может на самом деле оказаться непростым, но с ней мы ничего не сделаем, я думаю.

Предлагаю в течение недели обсудить полученные данные и описанные выше организационные моменты. Если новых критичных возражений не появится - сделаем канал.

**Comment by chabapok** [comment]
А это ничего, что 16 из 27 простых вопросов были заданы одним пользователем?

То есть фактически, статистика довольно сильно зависит от этого одного пользователя. И что это означает: пользователь научился - и больше таких вопросов не задает. Новых подобных ему не пришло (я не видел).
То есть, если взять статистику за другую неделю, она будет совсем другой.

Мне кажется, этот весь статистический анализ - это все ерунда. Если есть большое желание, то можно ничего не анализировать, а создать канал. Признаком того, что оно прижилось, будет то, что на этом канале новичам будут нормально помогать. Возможно даже, будут помогать быстрей чем сейчас, т.к. были люди которые писали, что помогали бы в новичковом канале интенсивней, чем помогают в general. Но может и нет. Мне кажется сейчас, что пока это не попробуешь - не узнаешь.

Критерий предлагаю такой. Если у нас возникнет такая ситуация, что новичок задал вопрос, ждет какое-то время, а потом задает его же в general - то это будет означать, что идея с каналом для новичков не прижилась, и надо от нее отказываться. А если подобных инцидентов не будет (или будет мало), то значит - прижилось.

Только надо сразу сказать, что мы не будем считать навязчивым поведением копипасту вопроса из новичкового канала в дженерал, если выждано адекватное время. 

Касаемо появления непростых вопросов в новичковом канале. Я думаю, что правильным поведением будет отвечать на такой вопрос в том же канале. Возможно, можно сказать мол, тут сложно, пойдем это обсуждать в дженерал. Там надо по ситуации смотреть.

**Comment by mkpankov** [comment]
@chabapok разумные аргументы.

Давайте создавать. Отпишусь здесь, когда будет готово.

**Comment by mkpankov** [comment]
Готово: https://gitter.im/ruRust/easy .

Ребята, нужен модератор с хорошими нервами, чтобы не злиться на новичков. Кто вызовется?

**Comment by vitvakatu** [comment]
@mkpankov в обязанности модератора что входит?

**Comment by mkpankov** [comment]
@vitvakatu обеспечение выполнения этих правил: https://rustycrate.ru/rules.html

**Comment by vitvakatu** [comment]
@mkpankov я могу.
- спокойно отношусь к любым, даже глупым вопросам
- правила насколько я помню не нарушал
- онлайн не менее часа ежедневно, чаще всего вообще большую часть дня

**Comment by mkpankov** [comment]
@vitvakatu добавлю тебя, как только смогу. У Gitter какой-то баг, из-за которого я не могу сделать тебя модератором комнаты. Связался с их поддержкой.

**Comment by mkpankov** [comment]
@vitvakatu добавил.
