### ISSUE TITLE
Стоит ли дописать запрет на варез в правила?

### ISSUE THREAD

**Issue by ozkriff** [ruRust/rustycrate.ru#212]
Спорная тема, конечно, но по мне серьезное сообщество такое поощрять не должно.

**Comment by mkpankov** [comment]
А есть прецеденты?

**Comment by vitvakatu** [comment]
@mkpankov да, был один. Впрочем, сейчас ссылка из чата гиттера удалена автором.

**Comment by mkpankov** [comment]
Тогда стоит дописать.

**Comment by shmutalov** [comment]
OMG

**Comment by shmutalov** [comment]
Что подразумевается под словом _варез_?

**Comment by ozkriff** [comment]
Незаконно распространяемые в сети объекты авторского права: ПО, книги, видео, изображения и т.п.

**Comment by shmutalov** [comment]
Эх...

**Comment by ozkriff** [comment]
@shmutalov речь же не о том что бы конфисковать у тебя с жесткого диска все нажитое. Мест где обсудить-передать это дело и кроме гиттера сообщества не мало :-)

**Comment by vitvakatu** [comment]
Никто не запрещает делать что угодно в личных сообщениях, но в официальных чатах - лучше не надо.
