### ISSUE TITLE
Заявка на создание новой комнаты для общения на тематику сети 

### ISSUE THREAD

**Issue by shmutalov** [ruRust/rustycrate.ru#217]
~~Не~~нужно открыть новую комнату для человеков, которые больше разбираются или хотели бы разбираться в сетевых технологиях. Ну там настройка проксей, фаерволов ~~, как правильно обжимать кабели~~ и т.д.

Варианты:
- ~~ruRust/cemeBuk~~
- ruRust/networking
- ruRust/sysadmin
- ~~ruRust/cucagMuH~~

**Comment by shmutalov** [comment]
БОЛЬШЕ КОМНАТ БОГУ КОМНАТ!!111

**Comment by Gordon-F** [comment]
@shmutalov это толстый троллинг или действительно заявка на улучшение?

**Comment by shmutalov** [comment]
@Gordon-F это не троллинг. Если уж развивать сообщество, то почему бы и нет? `infosec` есть, `webdev` есть, `gamedev` есть. Даже людей с сишарп канала позвал, потому что тема общая )

**Comment by mkpankov** [comment]
Нерешённые вопросы:
* Кто будет модератором?
* Сколько людей заинтересованы в этом канале?

Ниже моё личное мнение. Это отправная точка для обсуждения, а не отказ в создании комнаты.

Прошу не использовать существующие каналы как прецедент и мотивацию для нового.

Идея создания algo, webdev и infosec была в том, чтобы позволить людям из нашего сообщества, которые разбираются в смежных темах, нести знания людям. Я надеялся, что в итоге это будет означать и написание статей нашим сообществом - и rustycrate.ru перестал бы быть сайтом только про Rust, у нас появились бы "хабы" как на хабре. Т.е. большая часть ценности сообщества в том, чтобы писать качественные статьи и делать хорошие переводы, а в случае с этими каналами этого нет. Возможно потому, что необходимость написания статей никак и не афишировалась. Возможно потому, что технически хабов на сайте сейчас нет. Как бы то ни было.

Как неоднократно замечали другие участники, в algo, webdev и infosec мало активности. В данный момент я не уверен, что даже их существование оправдано. Это отдельный вопрос, но я рассказываю про это здесь, т.к. с новым каналом про сети наверняка получится так же, если делать так же, как с предыдущими.

gamedev особняком, потому что там активности всегда было много, и она держится на совместной работе и большом количестве проектов, которые ведут участники. Это, навскидку, канал с наибольшей плотностью проделанной работы к обсуждениям - при ~50 участниках, делается несколько игр и библиотек (порядка 10).

Поэтому если мы хотим создавать канал про сети, нужно решить вопрос ценностей сообщества. Как я говорил выше, я считаю, что большая часть нашей экспертизы и ценности в случае Rust в статьях и книгах. Думаю, с сетями нужно также заниматься этими вещами, чтобы оправдать появление нового канала.

Также замечу, что сети (networking) и администрирование сетей (sysadmin) это несколько разные темы. Мои ожидания таковы, что первая касается сетевого программирования и общего устройства сетей, но не касается собственно администрирования.

**Comment by vitvakatu** [comment]
@mkpankov согласен по всем пунктам.

**Comment by shmutalov** [comment]
> Прошу не использовать существующие каналы как прецедент и мотивацию для нового.

Почему нельзя? 

> Также замечу, что сети (networking) и администрирование сетей (sysadmin) это несколько разные темы. Мои ожидания таковы, что первая касается сетевого программирования и общего устройства сетей, но не касается собственно администрирования.

Я знаю, но эти две области тесно связаны, как и администрирование с программированием, как сетевые технологии с тем же программированием. Я написал несколько названий на вскидку, не обязательно прям точь-в-точь создавать комнату с такими названиями. Если быть точнее, я хотел бы видеть комнату сисадминов, сетевики как-то железякам, хотя... Я запутался :(

Идея была в том, чтобы я (мы?) могли приглашать знакомых в место, где можно общаться. Допустим, я знаю одного друга сисадмина эникейщика, он бы своих пригласил. Кого не встречал, в основном в скайпе люди сидят, и только через знакомых можно к ним обратится, если бывают проблемы.

Почему это не может быть любым другим форумом? Форумы буквально устарели, эти ббски, phpBBшки, вбюллитени прошлый век :) На них только торренты крутятся. Люди сейчас сидят или в соцсетях, или в чатах (телеграм, дискорд, шлак, гитр)

Я не говорю что есть особая нужда в таком канале, но иметь его было бы плюсом. Потому как можно было без лишних телодвижений людей приглашать в раст каналы, заинтересовывать их.

**Comment by mkpankov** [comment]
> Почему нельзя?

Потому что нет ощущения, что создать algo, webdev и infosec было хорошей идеей.

> Идея была в том, чтобы я (мы?) могли приглашать знакомых в место, где можно общаться. Допустим, я знаю одного друга сисадмина эникейщика, он бы своих пригласил. Кого не встречал, в основном в скайпе люди сидят, и только через знакомых можно к ним обратится, если бывают проблемы.

Хорошо. Сколько это человек, примерно?

Вопрос модерации канала всё ещё открыт.

**Comment by shmutalov** [comment]
> Потому что нет ощущения, что создать algo, webdev и infosec было хорошей идеей.

Ну webdev немного приживается. 

> Сколько это человек, примерно?

Лично моих знакомых 2 человека, хотя могу еще 2 найти. Я конечно понимаю, канал может стать заброшенным даже имея 4 человека (даже мне смешно :( )

> Вопрос модерации канала всё ещё открыт.

Кто-нибудь из текущих модераторов.

**Comment by ozkriff** [comment]
> Кто-нибудь из текущих модераторов.

ты же понимаешь, что "инициатива - дело наказуемое"? ;-)

**Comment by shmutalov** [comment]
@ozkriff ну я бы не хотел быть модератором )  Но можно

**Comment by vitvakatu** [comment]
Я могу быть модератором, если на то пошло. Все равно канал будет пустовать :smile:

**Comment by mkpankov** [comment]
> Лично моих знакомых 2 человека, хотя могу еще 2 найти. Я конечно понимаю, канал может стать заброшенным даже имея 4 человека (даже мне смешно :( )

Пожалуй, это основная проблема.

С другой стороны, если вы будете ну прямо очень активно общаться, можно сделать.

Что остальные думают насчёт этой идеи с новой комнатой?

**Comment by Gordon-F** [comment]
@mkpankov а есть какая-то статистика о том, как хорошо выстрелила идея создавать сообщества не связанные с Rust ? 

Если это идея в целом провалилась, то лучше новых комнат не создавать. И к тому же убрать не активные.

**Comment by mkpankov** [comment]
@Gordon-F число участников и сообщений. Есть heatmap по числу сообщений и число участников:

* webdev: 28, https://gitter.im/ruRust/webdev/archives/all
* algo: 23, https://gitter.im/ruRust/algo/archives/all
* infosec: 21, https://gitter.im/ruRust/infosec/archives/all

Я бы сказал что такая оценка говорит в пользу webdev и не в пользу algo и infosec.

**Comment by Gordon-F** [comment]
@mkpankov Как мне кажется в целом вся идея не взлетела. Поэтому может лучше не стоит создавать ещё одну комнату, которая умрет ?

Если сообщество само сформируется в оффтопике, general в отдельное подсообщество  и с общими интересами и (как gamedev) и создаст запрос на создание комнаты и этот запрос будет поддержан многими участниками, то такой запрос определено стоит поддержать.

**Comment by Vinatorul** [comment]
Я думаю, что algo и infosec не взлетели, потому что у нас нет того костяка, который бы целыми днями был готов обсуждать алгоритмы/инф безопасность, чтобы поддерживать каналы активными, даже когда у остальных нет вопросов. Вопросы по тем же алгоритмам возникают чаще всего в рамках другой дискуссии - не отправлять же человека задавать этот вопрос в algo, если на него можно в прямо здесь в несколько строк. А то получается какая-то бюрократия: "Извините, в этом окне мы только выдаём справки вида 1, для получения справки вида 1а пройдите в соседнее окно".

**Comment by shmutalov** [comment]
Хорошо. Не надо создавать комнату. Кому закрывать issue?

**Comment by mkpankov** [comment]
@shmutalov закрывай, если считаешь, что обсуждение закончено
