### ISSUE TITLE
Перевод "Rust and CSV parsing"

### ISSUE THREAD

**Issue by JIghtuse** [ruRust/rustycrate.ru#218]
Взялся переводить [Rust and CSV parsing](http://blog.burntsushi.net/csv/).

**Comment by mkpankov** [comment]
@JIghtuse есть успехи?

**Comment by JIghtuse** [comment]
@mkpankov примерно половину осилил, к сожалению редко удаётся время выделить.

**Comment by mkpankov** [comment]
Пока закрываю, если есть желание продолжить - переоткрывайте
