### ISSUE TITLE
Перевод новости о выпуске Rust 1.20

### ISSUE THREAD

**Issue by Gordon-F** [ruRust/rustycrate.ru#235]
https://blog.rust-lang.org/2017/08/31/Rust-1.20.html

Кто готов?

**Comment by vitvakatu** [comment]
Me, уже начал

**Comment by ozkriff** [comment]
К понедельнику, как обычно?

**Comment by vitvakatu** [comment]
Предоставлю сегодня PR, но когда везде выкладывать - не знаю
