### ISSUE TITLE
Добавить в словарь переводы новых слов.

### ISSUE THREAD

**Issue by bmusin** [ruRust/rustycrate.ru#252]
Добрый день.
Предлагаю добавить(в скобках варианты переводы):
* **macro**: "Макро-определение" или "макрос",
* **NLL(Non-lexical Lifetime)**: "Нелексическое время жизни",
* **expression**: "Выражение",
* **arm**(связано с `match`): "Ветка".
* **parse**: ?
* **crash**: "Аварийное завершение(сущ.)", "Аварийно завершиться(глаг.)",
* **handle**: ?

**Comment by ozkriff** [comment]
Я бы только оригинальный термин указал не только как аббревиатуру, но и полностью - "Non-lexical lifetimes (NLL)".

**Comment by mkpankov** [comment]
За чем дело встало? Pull request и вперёд - там и обсудим термины и предложим переводы.

**Comment by ozkriff** [comment]
parse и handle, мне кажется, надо по ситуации переводить. как тут один вариант универсальный предложишь?

**Comment by mkpankov** [comment]
Согласен, хотя общее "разбор" и "дескриптор" как вариант по умолчанию подходит

**Comment by BORN2LOSE** [comment]
Выполнено в https://github.com/ruRust/rustycrate.ru/pull/255
