### ISSUE TITLE
Добавление ссылки на перевод quickstart в шапке rustycrate.

### ISSUE THREAD

**Issue by bmusin** [ruRust/rustycrate.ru#253]
Добрый вечер.

Имеется перевод [на Gist][gist].
https://doc.rust-lang.org/book/second-edition/ch02-00-guessing-game-tutorial.html

Ссылка на Google Docs документ в чате, там можно вносить правки.
Сделаю PR, когда перевод будет вычитан.

Предлагаю запостить это на rustycrate и в его шапке разместить ссылку на этот перевод.
На мой взгляд, это будет удобно для новичков.
Официальный сайт, к слову, этого не содержит, и для того, чтобы добраться до этого tutorial,
приходиться делать около 5(!) кликов.

[gist]: https://gist.github.com/bmusin/78d58ea807e12733185b2627fea76fa3

**Comment by mkpankov** [comment]
Спасибо за перевод.

Его нужно делать в рамках перевода новой книги, не думаю, что есть смысл обособленно ссылаться на одну главу.

Перевод новой книги пока под вопросом.

**Comment by vitvakatu** [comment]
Мое мнение - можно добавить данный туториал в виде статьи на сайт. Когда (если) будет переводится новая книга - перевод можно перенести туда.

**Comment by mkpankov** [comment]
Отдельная ссылка точно не будет добавляться, на добавление в виде статьи есть PR.
