### ISSUE TITLE
Словарь: Добавить переводы "concurrency", "parallelism" и "multithreading"

### ISSUE THREAD

**Issue by ozkriff** [ruRust/rustycrate.ru#262]

**Comment by ozkriff** [comment]
Есть впечатление что в рунете закрепились варианты первода

- concurrency - параллельность
- parallelism - многопоточность

что выглядит немного странно и 100% путает кучу людей.

**Comment by XX** [comment]
@ozkriff Действительно, Википедия из concurrency перенаправляет на [параллелизм](https://ru.wikipedia.org/wiki/%D0%9F%D0%B0%D1%80%D0%B0%D0%BB%D0%BB%D0%B5%D0%BB%D0%B8%D0%B7%D0%BC_(%D0%B8%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%82%D0%B8%D0%BA%D0%B0))
Вот определение оттуда:

> параллели́зм — это свойство систем, при котором несколько вычислений выполняются одновременно, и при этом, возможно, взаимодействуют друг с другом. Вычисления могут выполняться на нескольких ядрах одного чипа с вытесняющим разделением времени потоков на одном процессоре, либо выполняться на физически отдельных процессорах.

Однако ниже дается примечание, которое несколько противоречит этому определению:

> В русскоязычной литературе нередко путаются термины «параллелизм» и «конкурентность». Оба термина означают одновременность процессов, но первый — на физическом уровне (параллельное исполнение нескольких процессов, нацеленное только на повышение скорости исполнения за счёт использования соответствующей аппаратной поддержки), а второй — на логическом (парадигма проектирования систем, идентифицирующая процессы как независимые, что в том числе позволяет их исполнять физически параллельно, но в первую очередь нацелено на упрощение написания многопоточных программ и повышение их устойчивости).

**Comment by mkpankov** [comment]
Что в итоге? Будем добавлять?

**Comment by ozkriff** [comment]
Да чего-то запутанно все, надо хоть о вменяемых вариантах договориться.

Как насчет

- "parallelism" - "параллелизм"
- "multithreading" - "многопоточность"
- "concurrency" - "конкурентность" ? :-\

?
