### ISSUE TITLE
Разработать документ регламентирующий правила синхронизации переводов книг

### ISSUE THREAD

**Issue by andreevlex** [ruRust/rustycrate.ru#266]
Обсуждение на форуме:

https://forum.rustycrate.ru/t/dalnejshaya-sudba-rbe-i-perevod-drugih-knig/306/13

**Comment by andreevlex** [comment]
@Gordon-F С чего начнем?

**Comment by mkpankov** [comment]
@andreevlex начать нужно с того, чтобы расписать подробный алгоритм работы с переводом, т.е. досконально, до конкретных команд гита, описать здесь пункт 4. и 5.

1.    Первое издание в архив
1.    Второе издание книги берем переведенное и вычитываем
1.   RBE делаем новый репозиторий и вносим туда уже переведенное
1.    Синхронизация переводов производится с использованием 2-х веток с оригиналом и переводом.
1.    Сравнение переводов производится по diff файла, а не diff commits.

**Comment by Gordon-F** [comment]
@mkpankov по поводу пункта 1. а зачем информация о книге в этом документе?

Это же должен быть регламент для работы с подобными проектами. Разве нет ?

**Comment by mkpankov** [comment]
@Gordon-F Это копия сообщения @andreevlex с форума для контекста. Здесь речь конкретно о пунктах 4 и 5

**Comment by mkpankov** [comment]
Перенёс https://github.com/ruRust/community/issues/5
