### ISSUE TITLE
Перевод "Pattern matching"

### ISSUE THREAD

**Issue by XX** [ruRust/rustycrate.ru#268]
Нужно решить, как лучше переводить термин **pattern matching**. Самый близкий перевод, по видимому, это "сопоставление с образцом". Но как лучше дальше по тексту называть **pattern**? В некоторых статьях и в первом издании книги используются термины "шаблон" и "образец" как взаимозаменяемые.

**Comment by vitvakatu** [comment]
Я за то, чтобы называть pattern - паттерн (образец). "Шаблон" имеет другое значение (template). В тексте можно говорить "сейчас посмотрим на сопоставление с образцом... образцы (patterns) должны ...."

**Comment by ozkriff** [comment]
Я полностью за ~~мокросту...~ "образец".

**Comment by mkpankov** [comment]
Вроде обсудили, надо добавить
