### ISSUE TITLE
Пересмотреть способ обсуждения статей

### ISSUE THREAD

**Issue by mkpankov** [ruRust/rustycrate.ru#281]
Сейчас есть несколько способов обсудить статью:

* комментарии на Disqus
* тема на форуме (для своих статей я создаю их вручную)
* реддит /r/rustycrate

Это избыточно. При этом Disqus-комментариев не было уже 7 месяцев. Последние были под анонсом питерского gamedev-митапа.

Я думаю, для митапов комментарии можно перенаправить в обсуждения на Meetup.com. Для всего остального - можно на реддит, для конкретных вопросов - на форум.

Комментарии под старыми статьями можно оставить.

**Comment by ozkriff** [comment]
Да было бы что перенаправлять, нет? Вродеж комментарии во всех этих трех каналах совсем штучные.

**Comment by mkpankov** [comment]
Да, штучные. Я и говорю - тот небольшой объём вопросов, который есть, можно попросить задавать в других местах. Необходимость Disqus для меня очень сомнительна сейчас.

**Comment by ozkriff** [comment]
Согласен, по мне форума и реддита, если на то или другое делать ссылки в конце статей, вполне хватит.

**Comment by OrKoN** [comment]
Я делаю сервис для комментариев, альтернативу disqus https://just-comments.com/

Может вам подойдет, если есть необходимость.
