### ISSUE TITLE
Переделать главное меню сайта

### ISSUE THREAD

**Issue by mkpankov** [ruRust/rustycrate.ru#285]
Нужно ориентироваться на задачу, из-за которой человек пришёл на сайт.

Среди прочего, стоит вынести социальные сети в главное меню.

**Comment by mkpankov** [comment]
Я начал готовить новую структуру, основанную на пользовательских сценариях. Предлагаю почитать-обсудить.

# Текущая структура

Здесь галочка обозначает, что этой странице найдено место в новой структуре.

- [x] Блог
- [x] Книги
  - [x] Словарь терминов
  - -
  - [x] Язык программирования Rust
  - [x] Маленькая книжка по макросам в Rust
  - [x] Растономикон
  - [x] Rust на примерах

- [x] Чаты
  - [x] Как подключиться через IRC и другие фишки Gitter
  - -
  - [x] Rust
  - [x] Разработка игр
  - [x] Информационная безопасность
  - [x] Веб-разработка
  - [x] Алгоритмы
  - [x] Диван - разговоры обо всём
  - [x] Об этом сайте
  - [x] О книгах, статьях, вопросах перевода

- Материалы сообщества
  - [x] Правила сообщества
  - [x] Правила перевода книг
  - [x] Документация по Cargo
  - [x] Проекты участников нашего сообщества
  - [x] Руководство по участию в проектах
  - [x] Редакционная политика
  - [x] Словарь терминов
  - [x] Статьи, над которыми мы работаем
  - [x] Команда
  - [x] Поддержали нас на Patreon

- [x] Кто использует Rust
- [x] Форум
- [x] Stackoverflow
- [x] GitHub
- [x] Поддержать!

# Новая структура

Названия пунктов верхнего уровня под вопросом. Сейчас они отражают название сценария, но т.к. они такие длинные их нельзя непосредственно использовать в меню.

- Я изучаю Rust
  - Книги
  - Статьи (руководства / обучение)
  - Документация по Cargo
- Подходит ли мне Rust?
  - Статьи (размышления)
  - Кто использует Rust
- Мне нужна помощь
  - Форум
  - Stackoverflow
  - ruRust/easy
- Хочу получать новости куда-то ещё
  - Подписка на RSS
  - Подписка по почте (нужно сделать)
- Что нового?
  - Статьи (новости)
  - Хабрахабр (обсудить этот пункт)
  - Социальные сети
    - Twitter
    - Facebook
    - Telegram
    - VK
    - Reddit
  - Все статьи
- Хочу пообщаться
  - Правила сообщества
  - Чаты
    - Список каналов
    - Руководство по Gitter (ранее Как подключиться через IRC и другие фишки Gitter)
    - Альтернативные клиенты чата - IRC, Matrix
  - Митапы
- Хочу поучаствовать в проекте
  - Проекты участников нашего сообщества
  - Как поучаствовать в проекте (ранее Руководство по участию в проектах)
- Пишу или перевожу
  - Программа поощрения авторов (ссылка на публикацию на форуме)
  - Словарь терминов
  - Статьи, над которыми мы работаем
  - Правила перевода книг
  - Редакционная политика
  - Как поучаствовать в проекте (ранее Руководство по участию в проектах)
- Поиск
- Хочу помочь сообществу
  - Деньгами
    - Поддержали нас на Patreon
    - Поддержать сообщество
  - Трудом
    - Активные проекты (новая страница)
    - GitHub
    - Как поучаствовать в проекте (ранее Руководство по участию в проектах)
- О сообществе
  - Команда

# Зачем приходит человек?

- Изучить Rust
  - Книги
  - Статьи (руководства / обучение)
  - Документация по Cargo
- Понять подходит ли ему Rust
  - Статьи (размышления)
  - Кто использует Rust
- Получить помощь
  - Форум
  - Stackoverflow
- Узнать новости
  - Статьи (новости)
  - Социальные сети
- Прочитать новые статьи
  - Все статьи
- Пообщаться
  - Чаты
    - Список каналов
  - Митапы

# Мотивация (неполный список)

- Развлечься
  - Пообщаться
  - Прочитать новые статьи
  - Узнать новости
- Помочь себе
  - Изучить Rust
  - Понять подходит ли ему Rust
  - Получить помощь
- Помочь кому-то
  - Проекты участников сообщества
- Помочь сообществу

**Comment by mkpankov** [comment]
Сделал 2 версии:

https://github.com/ruRust/rustycrate.ru/tree/menu
https://github.com/ruRust/rustycrate.ru/tree/menu-flat

Версия с вложенными страницами:
https://imgur.com/a/VB92SNJ
Плоская версия:
https://imgur.com/a/Gpt557a

**Comment by mkpankov** [comment]
@ruRust/site будьте добры, посмотрите, насколько это адекватно.

**Comment by Revertron** [comment]
По-моему, развёрнутые меню удобнее. Сразу понятно что и где есть, без лишних кликов.

**Comment by vitvakatu** [comment]
Аналогично, развернутые приятнее. Однако не смотрел сам состав пунктов еще

**Comment by mkpankov** [comment]
https://github.com/ruRust/rustycrate.ru/commit/63bc460cd8358bcdb0b9fe998691e49fb61f46a8
