### ISSUE TITLE
Словарь: перевод "inclusive range" и "exclusive range"

### ISSUE THREAD

**Issue by ozkriff** [ruRust/rustycrate.ru#290]
Нужно, как минимум, для новости про 1.26.
В переводе уже где-то оно есть? Или из математики, наверное, стоит перевод взять.

**Comment by XX** [comment]
@ozkriff В  математике есть термины "открытый интервал" и "закрытый интервал", но не знаю точно, как это по-английски.

**Comment by ozkriff** [comment]
https://en.wikipedia.org/wiki/Interval_(mathematics)#Including_or_excluding_endpoints + open/closed тоже используются.

Лично мне вариант "открытый диапазон" и "закрытый диапазон" кажутся ничегошным. Есть еще мнения?

**Comment by XX** [comment]
@ozkriff Вот Википедия пишет, что используется даже не "открытый и закрытый", а "открытый и замкнутый": https://ru.wikipedia.org/wiki/%D0%9F%D1%80%D0%BE%D0%BC%D0%B5%D0%B6%D1%83%D1%82%D0%BE%D0%BA_(%D0%BC%D0%B0%D1%82%D0%B5%D0%BC%D0%B0%D1%82%D0%B8%D0%BA%D0%B0)#%D0%A2%D0%B5%D1%80%D0%BC%D0%B8%D0%BD%D0%BE%D0%BB%D0%BE%D0%B3%D0%B8%D1%8F

**Comment by XX** [comment]
Можно еще писать несколько длиннее:
Диапазон, исключающий правую границу и дапазон, включающий правую границу.

**Comment by mkpankov** [comment]
Как перевели в итоге?

**Comment by ozkriff** [comment]
В переводе 1.26 в итоге использовано "закрытый/полуоткрытый диапазон".

**Comment by mkpankov** [comment]
Всё-таки в математике *интервал* и *промежуток*, откуда взялся диапазон?

**Comment by ozkriff** [comment]
> откуда взялся диапазон?

Эта часть из книги, вроде - http://rurust.github.io/rust_book_ru/src/iterators.html - насколько я вижу, там в основном уже используется "диапазон".

Лично я не имею мнения что из "интервал", "промежуток" или "диапазон" лучше.

**Comment by mkpankov** [comment]
Ок, но "закрытый" видимо надо поменять на "замкнутый".

https://ru.wikipedia.org/wiki/%D0%9F%D1%80%D0%BE%D0%BC%D0%B5%D0%B6%D1%83%D1%82%D0%BE%D0%BA_(%D0%BC%D0%B0%D1%82%D0%B5%D0%BC%D0%B0%D1%82%D0%B8%D0%BA%D0%B0)

**Comment by mkpankov** [comment]
Поменял
