### ISSUE TITLE
Добавить статью "IDE для Rust"

### ISSUE THREAD

**Issue by neooleg** [ruRust/rustycrate.ru#34]
В блоге критически нехватает поста об IDE, ибо фаворита в этом вопросе нет. Поэтому было бы полезно увидеть описание как стартовать с 2-3 топовыми решениями (и желательно без сборок, complex env, etc., т.к. это увеличивает порог вхождения для большинства).

Это очень важно для тех, кто начинает только щупать Rust!

**Comment by mkpankov** [comment]
Статью добавили, нужно расширить: описать настройку разных редакторов.

**Comment by mkpankov** [comment]
Сделано
