### ISSUE TITLE
Перенести навигацию из футера в заголовок, и сделать их не fixed

### ISSUE THREAD

**Issue by neooleg** [ruRust/rustycrate.ru#36]
### Problems/Motivation

1. При чтении контента весьма мешает внизу, будь то это часть браузера. Т.е. занимает полезную часть экрана и это при том, что верхнее меню пустое.
2. Это нарушет привычный UX, когда навигация всегда расположена в меню вверху.

### Solution

Использовать всем привычный [Bootstrap static top navbar](http://getbootstrap.com/examples/navbar-static-top/).

**Comment by mkpankov** [comment]
В целом согласен, но нижний убирать не хочу. В нижнем не навигация - там "О сайте", подписка и контакты. А это как раз - вот даже на этой странице GitHub - находится внизу.

**Comment by neooleg** [comment]
Да, но на GitHub футер не fixed (т.е. он виден только если доскролить до конца страницы), поэтому не мешает.

**Comment by mkpankov** [comment]
Не вопрос - фиксацию уберу, нижний оставлю.

**Comment by neooleg** [comment]
:+1:

**Comment by mkpankov** [comment]
Сделано
