### ISSUE TITLE
Описание Cargo

### ISSUE THREAD

**Issue by reddec** [ruRust/rustycrate.ru#37]
Катастрофически не хватает описания про сборщик Cargo. Мало даже в официальной документации, а та что есть, сильно фрагментирована.
Было бы здорово, если бы появилась статья описывающая:
- создание библиотеки и приложения
- подключение публичных решений
- выкладывание своих
- авто тестирование при сборке (если такое есть)
- лучшие практики

**Comment by l4l** [comment]
[Что на счет этого?](http://doc.crates.io/guide.html)

**Comment by D101101** [comment]
@l4l не знаю насколько это полное описание, но там нет как минимум про то, как [собирать либу и бинарник в одном проекте](http://stackoverflow.com/a/26946705/4777440)

**Comment by Gordon-F** [comment]
Как кратное описание - https://rurust.github.io/cargo-docs-ru/guide.html

**Comment by mkpankov** [comment]
Закрыли все пункты.

Первые три - https://rustycrate.ru/%D0%BE%D0%B1%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5/2017/12/17/crates.io.html
Четвёртый - 
https://rustycrate.ru/%D0%BE%D0%B1%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5/2017/07/30/rust-travis.html
и
https://rustycrate.ru/%D0%BE%D0%B1%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5/2017/08/20/rust-appveyor.html
Пятый - https://rustycrate.ru/%D1%80%D1%83%D0%BA%D0%BE%D0%B2%D0%BE%D0%B4%D1%81%D1%82%D0%B2%D0%B0/2016/05/06/good-practices-for-writing-rust-libraries.html
