### ISSUE TITLE
Статья про CI сервисы

### ISSUE THREAD

**Issue by Vinatorul** [ruRust/rustycrate.ru#40]
Думаю многим будет полезно появление на сайте статьи про использование различных `CI` сервисов, таких как `Travis`, `AppVeyor`, `Circle`, а также про использование `Homu`, `nightli.es`, `Coveralls` и других. С примерами скриптов и, возможно, сравнением.

**Comment by mkpankov** [comment]
Ссылка в тему: https://pascalhertleif.de/artikel/good-practices-for-writing-rust-libraries/

**Comment by ozkriff** [comment]
http://reangdblog.blogspot.com/2015/08/travis-ci.html

http://reangdblog.blogspot.com/2015/09/appveyor-travis-ci-windows.html

видели?

**Comment by Vinatorul** [comment]
Спасибо за ссылки.
По травису статья, правда, уже немного устарела (sudo используется, деплоя документации нет).
Про appveyor я сам мало что знаю, но конфиг там жуткий. Я сейчас взял свой - без сторонних библиотек он, конечно, намного приятнее. А то сразу вот таким монстром людей пугать как-то не хочется.

**Comment by ozkriff** [comment]
Про тревис - там упоминается вариант без sudo и его ограничения, можно дополнить подробностями. Развертки документации нет, потому что разговор идет о приложении, а не библиотеке - тоже можно просто дополнить :) .

Про appveyor - согласен, этот конфиг для уже относительно продвинутых пользователей)

**Comment by Vinatorul** [comment]
> Развертки документации нет, потому что разговор идет о приложении

Приложениям тоже нужна документация, но я уже придираюсь, да.

Я ещё дополню информацией о Coveralls и Homu.

**Comment by BORN2LOSE** [comment]
Думаю, что эту задачу можно закрыть, т.к. появилась статья на [сайте](https://rustycrate.ru/%D0%BE%D0%B1%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5/2017/07/30/rust-travis.html) от @mkpankov
