### ISSUE TITLE
Статья с советами по ведению проекта

### ISSUE THREAD

**Issue by Vinatorul** [ruRust/rustycrate.ru#45]
Я думаю многим, кто совершает свои первые шаги в opensource будет полезна статья вроде этой: https://manishearth.github.io/blog/2016/01/03/making-your-open-source-project-newcomer-friendly/

**Comment by mkpankov** [comment]
Думаю, в целом такая статья была бы полезна, но она в первую очередь для уже относительно больших устоявшихся проектов, куда люди могут захотеть отдавать свой код.

Для начинающих проект, я думаю, на первом этапе полезнее статья с лучшими практиками касательно самого кода, вроде [этой](https://pascalhertleif.de/artikel/good-practices-for-writing-rust-libraries/).

Её я читал, мне очень понравилось. Так что я всеми руками за неё.

**Comment by Vinatorul** [comment]
Да, отличная статья, можно либо певод сделать, либо что-нибудь своё на её основе. Но я бы ещё включил в неё рекомендации по грамотному оформлению проектов на github. Про то, как правильно работать с ветками, пулреквестами итд. Как контрибьютить в чужие проекты и потом не налететь на проблему с синхронизацией.

P.S. над статьёй про непрерывное интегрирование из соседнего Issue я потихоньку работаю.

P.P.S. идея сейчас пришла - сделать общую обзорную статью вроде той, что по ссылке, а потом каждый блок отдельно разобрать.

**Comment by defuz** [comment]
@ozkriff вчера говорил мне, что хочет перевести "Good Practices for Writing Rust Libraries"

**Comment by ozkriff** [comment]
Да, "Good Practices for Writing Rust Libraries" в процессе, постараюсь закончить на днях. Если не объявлюсь с ней к концу недели, то можно меня смело пинговать по этому поводу))

**Comment by mkpankov** [comment]
@ozkriff круто!

Кстати, думаю, надо по возможности держать отдельно переводы и переработанные статьи, либо отдельно обозначать что это дополненная и отредактированная тобой версия.

**Comment by ozkriff** [comment]
Вот, чет сделал: https://habrahabr.ru/post/280482

**Comment by ozkriff** [comment]
Если что, кстати, вот MD исходник: https://gist.github.com/ozkriff/fe88decb08d1bac1fa3b

**Comment by mkpankov** [comment]
@ozkriff PR сделаешь?

**Comment by ozkriff** [comment]
@mkpankov https://github.com/ruRust/rustycrate.ru/pull/93

**Comment by mkpankov** [comment]
Влито
