### ISSUE TITLE
Упразднить in-progress.md

### ISSUE THREAD

**Issue by ozkriff** [ruRust/rustycrate.ru#51]
Предлагаю упразднить in-progress.md, как-то неудобно делать кучу PR ради такого.

Лучше на каждую стоящую статью заводить по задаче с тегом типа "перевод статьи" прямо тут.

**Comment by defuz** [comment]
Есть еще вики: https://github.com/ruRust/rustycrate.ru/wiki

**Comment by mkpankov** [comment]
В целом согласен, сейчас я думаю что задачи лучше всего подходят для этого. Нужно будет завести метку.

Только метки нужно будет назначать тем, у кого есть доступ на запись.

Тогда ссылку на сайте нужно сделать на поиск по задачам с этой меткой.

**Comment by ozkriff** [comment]
@defuz Мне система управления задач видится более подходящим инструментом, все-таки перевод статьи - это вполне себе задача, за которой должен быть закреплен какой-то исполнитель и все такое.

**Comment by mkpankov** [comment]
https://github.com/ruRust/rustycrate.ru/labels/%D0%B2%20%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B5

**Comment by mkpankov** [comment]
Страницу убирать не стал - сделал пояснение, что список задач находится на GitHub. В остальном готово.
