### ISSUE TITLE
Решить вопрос с типографикой

### ISSUE THREAD

**Issue by mkpankov** [ruRust/rustycrate.ru#7]
Варианты:
* https://github.com/typograf/typograf

**Comment by mkpankov** [comment]
Если кто-то знает хорошее решение - просьба отписаться тут.

Задача: нужно типографировать тексты публикаций по правилам русского языка (ставить тире, кавычки, неразрывные пробелы где надо). Это нужно делать на сервере. Оптимально если типограф можно запускать на исходниках перед генерацией сайта, но не коммитить его результат - типографские символы затрудняют редактирование.

Нужно чтобы типограф понимал, где текст, который можно трогать, а где код и специальная разметка вроде YAML Front Matter - их нельзя типографировать.

**Comment by nesteruk** [comment]
Я в свое время просто сел, и года за 3 урывками реализовал типографику собственноручно. Вот собственно [проект](https://bitbucket.org/nesteruk/typografix), по сути он состоит из одного большого, гигантского `switch`-а, что наверняка не лучший дизайн, но все же. Вообщем даже если мой проект не портируем, он хорошо иллюстрирует те фичи которые я написал для публикации своих постов, и из него можно поворовать те идеи, которые понравятся.

**Comment by mkpankov** [comment]
Готово: https://github.com/ruRust/rustycrate.ru/commit/2ed286d02748c62260ba8bc83b29fd570e041d37
