### ISSUE TITLE
Установить общую терминологию для макросов

### ISSUE THREAD

**Issue by kstep** [ruRust/rustycrate.ru#75]
Нужно установить консенсус, как правильно и единообразно переводить термины при переводе текстов о макросах.

Ниже неполный перечень терминов и предлагаемых мной переводов. Обсуждаем.

- capture (`$e` в `($e:expr) => ...`) (noun) — **метапеременные**?
- capture (verb) — **захват метапеременных**? ...в метапеременные?
- token (noun) — **токен** ([термин](https://ru.wikipedia.org/wiki/%D0%A2%D0%BE%D0%BA%D0%B5%D0%BD))
- tokenize (verb) — **разбиение на токены**.
- token tree — **дерево токенов**.
- pattern (noun) — паттерн, **шаблон**, образец.
- match (verb) — **сопоставить с** **образцом**/шаблоном/паттерном.
- match (noun) — **сопоставление**? совпадение? соответствие?
- expand (verb) — раскрыть, **развернуть**.
- expansion (noun) — раскрытие, разворачивание, **развёртывание**.
- literal (noun) — **литерал** ([термин](https://ru.wikipedia.org/wiki/%D0%9B%D0%B8%D1%82%D0%B5%D1%80%D0%B0%D0%BB_(%D0%B8%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%82%D0%B8%D0%BA%D0%B0)))

**Comment by listochkin** [comment]
Паттерн - устоявшийся термин. Напрример, есго использует [статья в Википедии о регулярным выражениях](https://ru.wikipedia.org/wiki/%D0%A0%D0%B5%D0%B3%D1%83%D0%BB%D1%8F%D1%80%D0%BD%D1%8B%D0%B5_%D0%B2%D1%8B%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D1%8F).

**Comment by kstep** [comment]
@listochkin да, похоже. Но там он по-русски применяется тольео в одном месте. А в первом абзаце даются варианты употребимых вариантов перевода:

> pattern, по-русски её часто называют «шаблоном», «маской»

**Comment by mkpankov** [comment]
> - capture (`$e` в `($e:expr) => ...`) (noun) — метапеременные?
> - capture (verb) — захват метапеременных? ...в метапеременные?
> - token (noun) — токен ([термин](https://ru.wikipedia.org/wiki/%D0%A2%D0%BE%D0%BA%D0%B5%D0%BD))
> - tokenize (verb) — разбиение на токены.
> - token tree — дерево токенов.

Согласен
> - pattern (noun) — паттерн, шаблон, образец.

Шаблон, исключение в случае "pattern matching" - "сопоставление с образцом". Да, идиосинкразия, но сейчас во многих местах книги так. "Сопоставление с образцом" - устоявшийся перевод, но сам по себе "образец" не звучит совсем.

> - match (verb) — сопоставить с образцом/шаблоном/паттерном.

Сопоставить с образцом
> - match (noun) — сопоставление? совпадение? соответствие?

Сопоставление, так много где в книге написано и вроде нормально звучит
> - expand (verb) — раскрыть.

Я использовал "развернуть" в основном, насколько помню. В целом "раскрыть" наверное лучше, но предлагаю ради единства терминологии пока сделать "развернуть" здесь тоже.
> - expansion (noun) — раскрытие.

Аналогично.

По результатам обсуждения здесь нужно будет обновить [словарь](https://github.com/ruRust/rust_book_ru/wiki/%D0%A1%D0%BB%D0%BE%D0%B2%D0%B0%D1%80%D1%8C-%D1%82%D0%B5%D1%80%D0%BC%D0%B8%D0%BD%D0%BE%D0%B2)

**Comment by listochkin** [comment]
В той же статье capturing group modifiers переведены как модификаторы групп, слово "capture" просто опускают в переводе.

**Comment by kstep** [comment]
@mkpankov я правильно понял, что ты предлагаешь expansion = разворачивание?

**Comment by sumproxy** [comment]
может развертывание?

**Comment by kstep** [comment]
@listochkin да, но иногда capture стоит отдельно как сказумое, просто так не опустишь.

**Comment by mkpankov** [comment]
Народ, давайте не превращать задачу в чатик.

Если предлагаете изменение, пожалуйста, пишите, почему вы так считаете, чтобы обсуждение было аргументированным.

В режиме мозгового штурма лучше [в чате книги](https://gitter.im/ruRust/rust_book_ru) обсудить

**Comment by mkpankov** [comment]
@kstep @sumproxy

> @mkpankov я правильно понял, что ты предлагаешь expansion = разворачивание?

> может развертывание?

Посмотрел сейчас - существующий перевод использует "[развёртывание](http://rurust.github.io/rust_book_ru/src/macros.html#%D0%A0%D0%B0%D0%B7%D0%B2%D0%B5%D1%80%D1%82%D1%8B%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-expansion-%D0%A1%D0%B8%D0%BD%D1%82%D0%B0%D0%BA%D1%81%D0%B8%D1%81-%D0%BF%D1%80%D0%B5%D0%BE%D0%B1%D1%80%D0%B0%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-%D0%BC%D0%B0%D0%BA%D1%80%D0%BE%D0%BA%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D1%8B)"

**Comment by mkpankov** [comment]
Все со всем согласны?

**Comment by kstep** [comment]
Согласен. В описании тикета выбранные термины выделены жирным.

**Comment by mkpankov** [comment]
Спасибо, закрываю!
