### ISSUE TITLE
Перевести "Machine Learning in Rust"

### ISSUE THREAD

**Issue by alekseysidorov** [ruRust/rustycrate.ru#91]
https://athemathmo.github.io/2016/03/07/rusty-machine.html

Недавно как раз пробегала статья про ребят, которые самую быструю реализацию машинного обучения сделали. Там в статье она упоминается. 
Надеюсь, что получится понятная статья.

**Comment by antage** [comment]
Статья достаточно малосодержательная. Примеров использования почти нет. Стоит ли её переводить?

**Comment by alekseysidorov** [comment]
А есть альтернативы получше? Я вот на русских ресурсах вообще лишь одну новость на лоре про leaf видел. 
Думаю, что могу попробовать дополнить статью простеньким примером.

**Comment by mkpankov** [comment]
Я думаю, можно её перевести - она не такая большая.

**Comment by alekseysidorov** [comment]
Что-то я напрочь зарылся в попытках перевода терминологии, думаю пока это всё отложить в долгий ящик. Для начала бы мне неплохо было бы получше предметную область изучить.

**Comment by mkpankov** [comment]
Закрываю на данный момент, переоткрывайте если будет перевод
